### ISSUE TITLE
Release 0.1.0 

### ISSUE THREAD

**Issue by agconti** [agconti/not-it#10]
- [ ] Register touch events, give feedback to users #1 
- [ ] Create home screen. #3
- [x] Move index.js from /public to root so that gh-pages will render properly. #14
