### ISSUE TITLE
Release 0.4.0 

### ISSUE THREAD

**Issue by agconti** [agconti/not-it#13]
- [ ] CTA asking users to touch #2
- [ ] Fade home screen starting border away on touch #4
- [ ] Count Down #6
- [ ] Rest UI after user is chosen #9
